[WIP] Fix flakes with serverless e2e tests (#327)
Reusing connections in python2 is flaky. Just create a new connection every time. We don't use this code for stress tests, so the performance impact should not matter.

Example flake:
```
Exception ('The read operation timed out',) occurred
Traceback (most recent call last):
  File "/home/prow/go/src/github.com/GoogleCloudPlatform/esp-v2/tests/e2e/client/apiproxy_bookstore_quota_test.py", line 144, in <module>
    apiproxy_test.run_all_tests()
  File "/home/prow/go/src/github.com/GoogleCloudPlatform/esp-v2/tests/e2e/client/apiproxy_bookstore_quota_test.py", line 123, in run_all_tests
    self.verify_quota_control()
  File "/home/prow/go/src/github.com/GoogleCloudPlatform/esp-v2/tests/e2e/client/apiproxy_bookstore_quota_test.py", line 61, in verify_quota_control
    if response.status_code != 429:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

Signed-off-by: Teju Nareddy <nareddyt@google.com>