Various c++ fixes for google3 sync
1) Add missing bazel dependency
fatal error: 'google/api/quota.pb.h' file not found: #include "google/api/quota.pb.h"

2) Fix unused result warnings
error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
    AddDistributionMetric(size_distribution, m.name,
    LogsMetricsLoader::Load(origin_service, &logs, &metrics, &labels);
    request_builder_->FillCheckRequest(info, &request);

3) Remove un-used using statement
using ::google::protobuf::StringPiece;

4) Remove StringPiece (seems like it's not needed, makes import more complicated)
info.check_response_info.consumer_project_id = ::google::protobuf::StringPiece("12345");

5) Fix un-used lambda captures
error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
        [this, response, on_done](const Status& status,

6) Fix copy elision warning
third_party/cloudesf/src/envoy/http/service_control/filter.cc:44:14: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
    handler_ = std::move(factory_.createHandler(

Change-Id: Id2d1c5be62dc90b42d1a7b8708bb89def467f329